# Generated by Django 3.2.2 on 2021-05-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Brand_Kia', models.CharField(max_length=50)),
                ('Color_Red', models.CharField(max_length=50)),
                ('No_of_years', models.IntegerField()),
                ('Present_Price', models.FloatField()),
                ('Kms_Driven', models.IntegerField()),
                ('Owner', models.IntegerField()),
                ('Fuel_Type_Petrol', models.CharField(max_length=50)),
                ('Seller_Type_Individual', models.CharField(max_length=50)),
                ('Transmission_Manual', models.CharField(max_length=50)),
            ],
        ),
    ]
